"""Measurement records: schema, checks, JSON store.

Schema rule: only measured values are written to the file. Everything
computable (VeraCrypt header, NTFS metadata, used space, copy slack) is
computed on read and never saved. In the original manual records the
contradictions appeared precisely because of duplicated computable fields.
"""

from __future__ import annotations

import json
import os
import shutil
from dataclasses import dataclass, field, replace
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable, Sequence

from .factory import FactorySample, factory_data
from .paths import CALIBRATION_NAME
from .sizes import SUPPORTED_FS
from .model import (
    DEFAULT_CLUSTER_BYTES,
    MIB,
    VC_HEADER_BYTES,
    CopySlackModel,
    NtfsModel,
    SafetyModel,
    ceil_div,
    round_up,
)

SCHEMA_VERSION = 5

#: Schema 1 did not know file_alloc_bytes, schema 2 did not know filesystem,
#: schema 3 did not know the calibration key, schema 4 kept that key in one
#: file with the records. All of them are still read: a missing field means
#: exactly the old behaviour, and empty-volume measurements move on read first
#: from records to calibration, and from there to their own file. The new
#: version is always what gets written.
SUPPORTED_SCHEMAS = (1, 2, 3, 4, 5)

#: Plausibility bounds for NTFS metadata. The lower one catches lost digits
#: (Cache 2 has 36 573 written instead of 36 573 184). The upper one grows
#: with the volume: at 100 GiB $LogFile and $MFT alone give close to a hundred
#: megabytes, so a fixed ceiling here would give false alarms.
NTFS_MIN_BYTES = MIB
NTFS_MAX_FLOOR = 128 * MIB
NTFS_MAX_SHARE = 0.02


#: The scope an error invalidates. A record with a broken left_bytes still
#: gives a usable point for the NTFS model, and there is no need to lose it
#: because of that.
SCOPE_NTFS = "ntfs"
SCOPE_SLACK = "slack"
SCOPE_BOTH = "both"


@dataclass(frozen=True)
class Issue:
    code: str
    message: str
    scope: str = SCOPE_BOTH

    def affects(self, scope: str) -> bool:
        return self.scope in (scope, SCOPE_BOTH)


@dataclass
class Record:
    id: str
    container_mib: int
    created: str = ""
    mounted_bytes: int | None = None
    empty_free_bytes: int | None = None
    cluster_bytes: int = DEFAULT_CLUSTER_BYTES
    file_bytes: int | None = None
    file_count: int | None = None
    #: Σ ceil(size_i / cluster) × cluster, taken by walking the folder. For
    #: one file it is derived from file_bytes, for a folder it is not: the sum
    #: of logical sizes does not restore the per-cluster rounding of each file.
    file_alloc_bytes: int | None = None
    left_bytes: int | None = None
    #: Volume filesystem, read at measurement time. Empty means it was not
    #: read (all records from before the check appeared; by default they
    #: count as NTFS).
    filesystem: str = ""
    note: str = ""
    flagged: bool = False
    #: Disabled calibration point: the numbers stay in the file, but the
    #: factory value goes into the calculation. This way a "reset to factory"
    #: loses nothing.
    disabled: bool = False
    #: What the calculation promised when the container was created from it,
    #: and how much safety margin that promise held. Stored, because they
    #: cannot be computed after the fact: both models change with every new
    #: measurement, and a recalculation would answer "what would I say today",
    #: not "what did I say then".
    predicted_mib: int | None = None
    predicted_safety_mib: int | None = None
    #: File set key, if the data was generated by automatic collection. Empty
    #: means a real copy. The distinction matters: a file set describes the
    #: machine, not the user's data, and on another machine it has to be
    #: rebuilt.
    fileset: str = ""

    def __post_init__(self) -> None:
        if not self.created:
            self.created = datetime.now().isoformat(timespec="seconds")

    # --- computable values: never stored ------------------------------------

    @property
    def container_bytes(self) -> int:
        return self.container_mib * MIB

    @property
    def vc_header(self) -> int | None:
        if self.mounted_bytes is None:
            return None
        return self.container_bytes - self.mounted_bytes

    @property
    def ntfs_bytes(self) -> int | None:
        if self.mounted_bytes is None or self.empty_free_bytes is None:
            return None
        return self.mounted_bytes - self.empty_free_bytes

    @property
    def consumed_bytes(self) -> int | None:
        if self.empty_free_bytes is None or self.left_bytes is None:
            return None
        return self.empty_free_bytes - self.left_bytes

    @property
    def is_calibration_point(self) -> bool:
        """Empty-volume measurement: neither data nor left space after copying.

        No separate field is kept — the flag is derived. A calibration point
        is defined precisely by nothing having been put into the container.
        """
        return self.file_bytes is None and self.left_bytes is None

    @property
    def payload_alloc(self) -> int | None:
        """Space taken by the data itself, including rounding to clusters.

        The measured value takes priority over the derived one: for a folder
        of many files round_up(Σ size_i) is less than Σ round_up(size_i), and
        the difference would all end up in copy slack.
        """
        if self.file_alloc_bytes is not None:
            return self.file_alloc_bytes
        if self.file_bytes is None:
            return None
        return round_up(self.file_bytes, self.cluster_bytes)

    @property
    def copy_slack_measured(self) -> int | None:
        consumed = self.consumed_bytes
        alloc = self.payload_alloc
        if consumed is None or alloc is None:
            return None
        return consumed - alloc

    # --- checking the prediction after the fact ----------------------------

    @property
    def minimum_mib(self) -> int | None:
        """The smallest container this data would still have fitted into.

        The used space on the volume is `mounted_bytes - left_bytes`, and it
        already includes everything: NTFS metadata, the cluster-rounded data
        and copy slack. Add the VeraCrypt header and round up to MiB — and you
        get the Container init that would have been just enough.

        The estimate is slightly high: a smaller container would give a
        smaller volume, and with it less metadata. The error goes towards
        overstating the minimum, that is, the miss comes out smaller than the
        real one — the metric errs on the side of alarm, not complacency, and
        that is the right side.
        """
        if self.mounted_bytes is None or self.left_bytes is None:
            return None
        return ceil_div(self.mounted_bytes - self.left_bytes + VC_HEADER_BYTES, MIB)

    @property
    def miss_mib(self) -> int | None:
        """Promised minus the minimum that would suffice.

        Plus is overestimate, zero is an exact hit, minus means **the data
        would not have fitted**. The value is computed for the sake of that
        last case: underestimate is the only dangerous side of the
        calculation.
        """
        minimum = self.minimum_mib
        if self.predicted_mib is None or minimum is None:
            return None
        return self.predicted_mib - minimum

    @property
    def model_miss_mib(self) -> int | None:
        """The same miss minus the intentional safety margin.

        Without this number the miss is ambiguous: +5 MiB looks the same both
        when the model is exact with a 5 MiB safety margin and when the model
        underestimated by 3 and 8 MiB of safety margin hid it. The second is a
        harbinger of failure that looks healthy.
        """
        miss = self.miss_mib
        if miss is None:
            return None
        return miss - (self.predicted_safety_mib or 0)

    @property
    def forecast_checked(self) -> bool:
        """Anything to compare: prediction recorded and left space measured."""
        return self.miss_mib is not None

    # --- serialisation ------------------------------------------------------

    def to_json(self) -> dict[str, Any]:
        data: dict[str, Any] = {
            "id": self.id,
            "created": self.created,
            "container_mib": self.container_mib,
            "cluster_bytes": self.cluster_bytes,
        }
        for name in (
            "mounted_bytes",
            "empty_free_bytes",
            "file_bytes",
            "file_count",
            "file_alloc_bytes",
            "left_bytes",
            "predicted_mib",
            "predicted_safety_mib",
        ):
            value = getattr(self, name)
            if value is not None:
                data[name] = value
        if self.filesystem:
            data["filesystem"] = self.filesystem
        if self.fileset:
            data["fileset"] = self.fileset
        if self.note:
            data["note"] = self.note
        if self.flagged:
            data["flagged"] = True
        if self.disabled:
            data["disabled"] = True
        return data

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> "Record":
        return cls(
            id=str(data.get("id", "")),
            created=str(data.get("created", "")),
            container_mib=int(data["container_mib"]),
            mounted_bytes=_opt_int(data.get("mounted_bytes")),
            empty_free_bytes=_opt_int(data.get("empty_free_bytes")),
            cluster_bytes=int(data.get("cluster_bytes", DEFAULT_CLUSTER_BYTES)),
            file_bytes=_opt_int(data.get("file_bytes")),
            file_count=_opt_int(data.get("file_count")),
            file_alloc_bytes=_opt_int(data.get("file_alloc_bytes")),
            left_bytes=_opt_int(data.get("left_bytes")),
            filesystem=str(data.get("filesystem", "")),
            note=str(data.get("note", "")),
            flagged=bool(data.get("flagged", False)),
            disabled=bool(data.get("disabled", False)),
            predicted_mib=_opt_int(data.get("predicted_mib")),
            predicted_safety_mib=_opt_int(data.get("predicted_safety_mib")),
            fileset=str(data.get("fileset", "")),
        )


def _opt_int(value: Any) -> int | None:
    return None if value is None else int(value)


def validate(record: Record) -> list[Issue]:
    """Five checks, each catching a real class of manual input error."""
    issues: list[Issue] = []

    if record.container_mib <= 0:
        issues.append(Issue("container_mib", "Размер контейнера должен быть больше нуля."))

    mounted = record.mounted_bytes
    free = record.empty_free_bytes

    if mounted is not None:
        header = record.container_bytes - mounted
        if header <= 0:
            issues.append(
                Issue(
                    "header",
                    f"Размер тома ({mounted}) не меньше размера контейнера "
                    f"({record.container_bytes}): заголовок VeraCrypt получается "
                    f"отрицательным.",
                    SCOPE_NTFS,
                )
            )
        elif header != VC_HEADER_BYTES:
            issues.append(
                Issue(
                    "header_unusual",
                    f"Заголовок VeraCrypt вышел {header} B вместо ожидаемых "
                    f"{VC_HEADER_BYTES} B. Проверьте container_mib и mounted_bytes.",
                    SCOPE_NTFS,
                )
            )

    if mounted is not None and free is not None:
        if free >= mounted:
            issues.append(
                Issue(
                    "free_ge_mounted",
                    f"Свободное место на пустом томе ({free}) не меньше его "
                    f"ёмкости ({mounted}).",
                )
            )
        else:
            ntfs = mounted - free
            ceiling = max(NTFS_MAX_FLOOR, int(mounted * NTFS_MAX_SHARE))
            if not (NTFS_MIN_BYTES <= ntfs <= ceiling):
                issues.append(
                    Issue(
                        "ntfs_range",
                        f"Метаданные NTFS вышли {ntfs} B — вне правдоподобного "
                        f"диапазона {NTFS_MIN_BYTES}..{ceiling} B. Похоже на "
                        f"потерю или лишние разряды.",
                        SCOPE_NTFS,
                    )
                )

    consumed = record.consumed_bytes
    alloc = record.payload_alloc
    if consumed is not None and alloc is not None and consumed < alloc:
        issues.append(
            Issue(
                "consumed_lt_file",
                f"Занято на томе {consumed} B, а сам файл занимает {alloc} B. "
                f"Занятое не может быть меньше файла — ошибка в одном из полей "
                f"empty_free_bytes / left_bytes / file_bytes.",
                SCOPE_SLACK,
            )
        )

    if record.filesystem and record.filesystem.upper() != SUPPORTED_FS:
        issues.append(
            Issue(
                "filesystem",
                f"Том отформатирован как {record.filesystem}, а модель "
                f"метаданных снята на {SUPPORTED_FS}. У других файловых систем "
                f"накладные расходы устроены иначе, и в калибровку такая "
                f"запись не идёт.",
                SCOPE_NTFS,
            )
        )

    alloc_measured = record.file_alloc_bytes
    if alloc_measured is not None:
        if record.file_bytes is not None and alloc_measured < record.file_bytes:
            issues.append(
                Issue(
                    "alloc_lt_logical",
                    f"Данные по кластерам ({alloc_measured}) меньше их логического "
                    f"размера ({record.file_bytes}). Округление вверх не может "
                    f"уменьшить объём.",
                    SCOPE_SLACK,
                )
            )
        if record.cluster_bytes > 0 and alloc_measured % record.cluster_bytes:
            issues.append(
                Issue(
                    "alloc_not_aligned",
                    f"Данные по кластерам ({alloc_measured}) не кратны размеру "
                    f"кластера ({record.cluster_bytes}).",
                    SCOPE_SLACK,
                )
            )

    if record.file_count is not None:
        if record.file_count < 1:
            issues.append(
                Issue(
                    "file_count",
                    "Количество файлов должно быть не меньше 1.",
                    SCOPE_SLACK,
                )
            )
        elif record.file_bytes is not None and record.file_count > record.file_bytes:
            issues.append(
                Issue(
                    "file_count_gt_bytes",
                    f"Файлов ({record.file_count}) больше, чем байт "
                    f"({record.file_bytes}).",
                    SCOPE_SLACK,
                )
            )

    return issues


def is_usable(record: Record, scope: str = SCOPE_BOTH) -> bool:
    """Whether the record is fit for calibrating the given model.

    What is checked is not "are there any errors at all" but whether they
    touch exactly the value that is taken from the record.
    """
    if record.flagged:
        return False
    if scope == SCOPE_BOTH:
        return not validate(record)
    return not any(issue.affects(scope) for issue in validate(record))


def ntfs_points(records: Iterable[Record]) -> list[tuple[int, int]]:
    """Points (volume size → NTFS metadata) for calibrating NtfsModel."""
    points = []
    for record in records:
        overhead = record.ntfs_bytes
        if overhead is not None and is_usable(record, SCOPE_NTFS):
            points.append((record.mounted_bytes, overhead))
    return points


def slack_samples(records: Iterable[Record]) -> list[tuple[int, int]]:
    """Pairs (file count → measured slack) for calibrating CopySlackModel."""
    samples = []
    for record in records:
        measured = record.copy_slack_measured
        if measured is None or not is_usable(record, SCOPE_SLACK):
            continue
        samples.append((record.file_count or 1, measured))
    return samples


def build_models(
    records: Sequence[Record],
) -> tuple[NtfsModel, CopySlackModel]:
    """Build both models from the accumulated records."""
    return (
        NtfsModel(ntfs_points(records)),
        CopySlackModel.calibrate(slack_samples(records)),
    )


def build_safety(
    records: Sequence[Record],
    factory_volumes: set[int] | None = None,
) -> SafetyModel:
    """Build the safety margin model from the accumulated records.

    The deviations are taken from the leave-one-out check: only it shows how
    the model behaves where there was no point. Scaling them to the width of
    the segment in question is left to SafetyModel — the raw deviation is
    taken on a gap about twice as wide as the real one.

    Beyond the edge of the measured range there is no local evidence at all,
    and the largest underestimate over all records goes there — deliberately
    cautious.
    """
    checks = ntfs_cross_check(records)
    deviations = [
        (check.record.mounted_bytes, check.deviation, check.record.id)
        for check in checks
        if check.record.mounted_bytes
    ]
    slack_deviations = [
        (check.record.file_count or 1, check.deviation, check.record.id)
        for check in slack_cross_check(records)
    ]
    return SafetyModel(
        ntfs=NtfsModel(ntfs_points(records)),
        ntfs_deviations=deviations,
        slack_deviations=slack_deviations,
        extrapolation_bytes=worst_shortfall(checks),
        factory_volumes=factory_volumes or set(),
    )


@dataclass(frozen=True)
class Check:
    """How well the model would have hit the record without seeing it."""

    record: Record
    measured: int
    predicted: int
    calibrated: bool

    @property
    def deviation(self) -> int:
        """A positive value means the model underestimated, i.e. missed low."""
        return self.measured - self.predicted


def ntfs_cross_check(records: Sequence[Record]) -> list[Check]:
    """Check the NTFS model, leaving the checked record out of calibration.

    Without leaving it out the check is meaningless: a piecewise-linear model
    passes exactly through its points, and the deviation would always be zero.
    """
    checks = []
    for index, record in enumerate(records):
        measured = record.ntfs_bytes
        if measured is None or not is_usable(record, SCOPE_NTFS):
            continue
        others = [*records[:index], *records[index + 1 :]]
        model = NtfsModel(ntfs_points(others))
        checks.append(
            Check(
                record=record,
                measured=measured,
                predicted=model.overhead(record.mounted_bytes),
                calibrated=model.calibrated,
            )
        )
    return checks


def slack_cross_check(records: Sequence[Record]) -> list[Check]:
    """The same for copy slack."""
    checks = []
    for index, record in enumerate(records):
        measured = record.copy_slack_measured
        if measured is None or not is_usable(record, SCOPE_SLACK):
            continue
        others = [*records[:index], *records[index + 1 :]]
        model = CopySlackModel.calibrate(slack_samples(others))
        checks.append(
            Check(
                record=record,
                measured=measured,
                predicted=model.slack(record.file_count or 1),
                calibrated=model.calibrated,
            )
        )
    return checks


def worst_shortfall(checks: Sequence[Check]) -> int:
    """Largest underestimate. Zero means the model underestimated nowhere."""
    return max((check.deviation for check in checks), default=0)


def slack_key(record: Record) -> str:
    """What tells copy-slack measurements apart — and what supersedes what.

    The key is the file set, not the file count. The file count would not do:
    two sets with `n = 1` are deliberately made different in size (64 MiB
    and 4 GiB), to compare them with each other and check that copy slack
    does not depend on file size. A key by `n` made them mutually exclusive —
    on the first real run the second silently ate the first together with
    its NTFS point, that is, the supersede rule destroyed exactly the
    reconciliation that both sets exist for.

    A measurement taken by hand has no file set, and it is still identified
    by the file count: two manual measurements at the same `n` are two
    measurements of the same thing.
    """
    return record.fileset or f"n={record.file_count}"


def factory_slack_record(sample: FactorySample) -> Record:
    """A factory copy-slack measurement as a record. Same numbers as the file.

    Such a record serves both models at once: its empty volume is measured,
    so it is also an NTFS point. That is by design — the measurement was
    taken on a real volume, and throwing away its metadata would be wasteful.
    """
    title = sample.title or sample.fileset
    return Record(
        id=f"Заводской запас {title}".strip(),
        created="",
        container_mib=sample.container_mib,
        cluster_bytes=sample.cluster_bytes,
        mounted_bytes=sample.mounted_bytes,
        empty_free_bytes=sample.empty_free_bytes,
        file_bytes=sample.file_bytes,
        file_count=sample.file_count,
        file_alloc_bytes=sample.file_alloc_bytes,
        left_bytes=sample.left_bytes,
        fileset=sample.fileset,
    )


@dataclass(frozen=True)
class Forecast:
    """Summary of checking the prediction after the fact.

    Computed over the records that have both the calculation's prediction
    and a measured left space. Everything else has nothing to check against.
    """

    checked: int
    worst_miss: int
    worst_model_miss: int
    #: Records where the promised container would not have been enough.
    #: Empty means the calculation never underestimated, and that is the main
    #: thing to know.
    short: tuple[str, ...]

    @property
    def any_short(self) -> bool:
        return bool(self.short)


def forecast(records: Iterable[Record]) -> Forecast:
    """How the calculation did on the records it can be compared against."""
    checked = [record for record in records if record.forecast_checked]
    if not checked:
        return Forecast(0, 0, 0, ())
    return Forecast(
        checked=len(checked),
        worst_miss=min(record.miss_mib for record in checked),
        worst_model_miss=min(record.model_miss_mib for record in checked),
        short=tuple(record.id for record in checked if record.miss_mib < 0),
    )


class StoreError(Exception):
    """The store is unavailable or corrupted."""


def calibration_file_for(records_file: str | os.PathLike[str]) -> Path:
    """The measurements file next to the records file, with a fixed name.

    The name is fixed, not derived from the records file name: measurements
    describe the machine, not a set of records, and two records files in one
    folder must share one calibration rather than breed two copies of the
    same numbers.
    """
    return Path(records_file).with_name(CALIBRATION_NAME)


def _read_json(path: Path) -> dict[str, Any]:
    """Read the file, check the schema version. A missing file is no error."""
    if not path.exists():
        return {}
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise StoreError(
            f"Файл {path} повреждён и не читается как JSON: {exc}. "
            f"Резервная копия: {path.with_suffix(path.suffix + '.bak')}"
        ) from exc
    except OSError as exc:
        raise StoreError(f"Не удалось прочитать {path}: {exc}") from exc

    version = raw.get("schema")
    if version not in SUPPORTED_SCHEMAS:
        supported = ", ".join(str(item) for item in SUPPORTED_SCHEMAS)
        raise StoreError(
            f"Версия схемы {version!r} не поддерживается, ожидается одна из: {supported}."
        )
    return raw


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    """Atomic write with a single .bak backup."""
    text = json.dumps(payload, ensure_ascii=False, indent=2)
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists():
            shutil.copy2(path, path.with_suffix(path.suffix + ".bak"))
        temp = path.with_suffix(path.suffix + ".tmp")
        temp.write_text(text, encoding="utf-8")
        os.replace(temp, path)
    except OSError as exc:
        raise StoreError(f"Не удалось записать {path}: {exc}") from exc


@dataclass
class Store:
    """Two JSON files: copy records and empty-volume measurements.

    Separate, because these are different values with different lifetimes.
    Copy records describe the data and move together with it; measurements
    describe the machine — the Windows build and the VeraCrypt version — and
    are wrong on another machine. In one file they had to travel together,
    and someone else's calibration arrived posing as your own.

    One store owns both files: the calculation stands on them together, and
    there would be nowhere to read them separately.
    """

    path: Path
    records: list[Record] = field(default_factory=list)
    calibration: list[Record] = field(default_factory=list)
    #: Where the measurements went. Empty means the neighbouring file with the
    #: fixed name.
    calibration_path: Path | None = None

    def __post_init__(self) -> None:
        self.path = Path(self.path)
        if self.calibration_path is None:
            self.calibration_path = calibration_file_for(self.path)
        else:
            self.calibration_path = Path(self.calibration_path)
        #: The measurements came from the old single-file store and have not
        #: yet been written to their own place. While that is so, the old file
        #: holds a copy of them.
        self.migrated = False

    @property
    def backup_path(self) -> Path:
        return self.path.with_suffix(self.path.suffix + ".bak")

    @classmethod
    def load(
        cls,
        path: str | os.PathLike[str],
        calibration_path: str | os.PathLike[str] | None = None,
    ) -> "Store":
        path = Path(path)
        points_path = (
            Path(calibration_path)
            if calibration_path is not None
            else calibration_file_for(path)
        )

        raw = _read_json(path)
        version = int(raw.get("schema", SCHEMA_VERSION))
        records = [Record.from_json(item) for item in raw.get("records", [])]

        # Measurements from the old single-file store. Before schema four they
        # were mixed in with the records, in schema four they had their own
        # key in the same file. The numbers do not change, only the place does.
        legacy = [Record.from_json(item) for item in raw.get("calibration", [])]
        if version < 4:
            legacy.extend(record for record in records if record.is_calibration_point)
            records = [record for record in records if not record.is_calibration_point]

        points = [
            Record.from_json(item)
            for item in _read_json(points_path).get("calibration", [])
        ]
        # The own measurements file outranks the arrived one: if the user has
        # already taken a point on this volume, the old copy from the records
        # file does not supersede it.
        covered = {record.mounted_bytes for record in points}
        points.extend(
            record for record in legacy if record.mounted_bytes not in covered
        )

        store = cls(
            path=path,
            records=records,
            calibration=points,
            calibration_path=points_path,
        )
        store.migrated = bool(legacy)
        return store

    def save(self) -> None:
        _write_json(
            self.path,
            {
                "schema": SCHEMA_VERSION,
                "records": [record.to_json() for record in self.records],
            },
        )
        # An empty measurements file is not created: on a new machine there are
        # no own points at all, and there is no reason to put a dummy next to
        # the records. One that has become empty is rewritten, otherwise the
        # deleted measurements would come back on the next read.
        if self.calibration or self.calibration_path.exists():
            _write_json(
                self.calibration_path,
                {
                    "schema": SCHEMA_VERSION,
                    "calibration": [record.to_json() for record in self.calibration],
                },
            )
        self.migrated = False

    def calibration_records(self) -> list[Record]:
        """Points that take part in the model: own enabled ones plus factory.

        An own measurement supersedes the factory one at the same volume size.
        Not "the larger of the two", as in NtfsModel._dedupe: the factory value
        was taken on another machine, and a smaller own value is truer than
        any foreign one.
        """
        own = [record for record in self.calibration if not record.disabled]
        covered = {record.mounted_bytes for record in own if record.mounted_bytes}
        covered.update(
            record.mounted_bytes for record in self.records if record.mounted_bytes
        )

        filled = list(own)
        for point in factory_data().points:
            if point.mounted_bytes in covered:
                continue
            filled.append(
                Record(
                    id=f"Заводская {point.container_mib} MiB",
                    created="",
                    container_mib=point.container_mib,
                    cluster_bytes=point.cluster_bytes,
                    mounted_bytes=point.mounted_bytes,
                    empty_free_bytes=point.empty_free_bytes,
                )
            )

        # Factory copy-slack measurements are superseded by own ones by file
        # count, not by volume size: copy slack depends on n, and an own point
        # at the same n is truer than a foreign one for exactly the same reason
        # as with the metadata.
        counts = {
            record.file_count
            for record in [*self.records, *own]
            if record.file_count and record.copy_slack_measured is not None
        }
        for sample in factory_data().samples:
            if sample.file_count in counts:
                continue
            filled.append(factory_slack_record(sample))
        return filled

    def all_for_model(self) -> list[Record]:
        """Everything the model is built on: copy records and points."""
        return [*self.records, *self.calibration_records()]

    def calibration_points(self) -> list[Record]:
        """Own empty-volume measurements — what the coverage table shows."""
        return [record for record in self.calibration if record.is_calibration_point]

    def slack_measurements(self) -> list[Record]:
        """Own copy-slack measurements.

        They live in the same file as the calibration points: both values
        describe the machine, not the data, and are equally wrong on another
        machine. No separate field tells them apart — the flag is derived,
        like everything else computable: a copy-slack measurement has both
        data and left space, so it does not count as a calibration point.
        """
        return [
            record for record in self.calibration if not record.is_calibration_point
        ]

    def put_calibration(self, record: Record) -> None:
        """Put a measurement, superseding the previous one of the same kind.

        Superseding is separate: a calibration point replaces the point on
        the same volume, a copy-slack measurement replaces the measurement of
        the same file set. A shared key by `mounted_bytes` would knock out an
        NTFS point with a copy-slack measurement taken at the same volume
        size, and vice versa — silently, because both records look equally
        legitimate.
        """
        if record.is_calibration_point:
            keep = [
                item
                for item in self.calibration
                if not item.is_calibration_point
                or item.mounted_bytes != record.mounted_bytes
            ]
        else:
            key = slack_key(record)
            keep = [
                item
                for item in self.calibration
                if item.is_calibration_point or slack_key(item) != key
            ]
        self.calibration = [*keep, record]

    def factory_volumes(self) -> set[int]:
        """Volume sizes covered only by factory data.

        Copy-slack measurements also give an NTFS point — the empty volume is
        measured before the files are written — so the factory ones among
        them count here on a par with the points: a segment whose both ends
        are foreign must get the factory margin regardless of which
        collection took the foreign numbers.
        """
        own = {
            record.mounted_bytes
            for record in [*self.records, *self.calibration]
            if record.mounted_bytes and not record.disabled
        }
        volumes = {point.mounted_bytes for point in factory_data().points}
        volumes.update(sample.mounted_bytes for sample in factory_data().samples)
        return {volume for volume in volumes if volume not in own}

    def models(self) -> tuple[NtfsModel, CopySlackModel]:
        return build_models(self.all_for_model())

    def safety(self) -> SafetyModel:
        return build_safety(self.all_for_model(), self.factory_volumes())

    def add(self, record: Record) -> None:
        self.records.append(record)

    def replace_at(self, index: int, record: Record) -> None:
        self.records[index] = record

    def index_of(self, record: Record) -> int | None:
        """Where this very record lies. By identity, not by equality.

        Edit windows are modeless, and while one of them is open, the list has
        time to change: a neighbouring record was deleted, a new one added —
        the index taken at opening already points to someone else's row.
        Equality does not work here either: two records with identical fields
        are common, `Record` compares by value, and the edit would go into
        whichever came first.

        None means the record is no longer in the store: it was deleted from
        another window.
        """
        for index, item in enumerate(self.records):
            if item is record:
                return index
        return None

    def remove_at(self, index: int) -> None:
        del self.records[index]

    def measure_into(self, record: Record, total: int, free: int) -> Record:
        """Spread one volume measurement over the record's fields.

        An empty volume gives the capacity and the free space; the same
        measurement after copying gives the left space. Which field gets
        filled is decided by whether empty_free_bytes is already filled.
        """
        if record.empty_free_bytes is None:
            return replace(record, mounted_bytes=total, empty_free_bytes=free)
        return replace(record, left_bytes=free)
